'use strict';

/**
 * Dataset generator shared by `npm run seed` and `npm run benchmark` so the
 * two can never drift apart.
 *
 * Assumes mongoose is ALREADY connected — the caller owns the lifecycle.
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const User = require('../../src/models/User');
const Workspace = require('../../src/models/Workspace');
const Task = require('../../src/models/Task');
const ActivityLog = require('../../src/models/ActivityLog');

const STATUSES = ['todo', 'doing', 'done'];
const PRIORITIES = ['low', 'medium', 'high', 'urgent'];
const LABELS = ['backend', 'frontend', 'infra', 'bug', 'docs', 'design', 'perf', 'security'];

const pick = (arr, rnd) => arr[Math.floor(rnd() * arr.length)];
const randInt = (rnd, min, max) => min + Math.floor(rnd() * (max - min + 1));
const randDate = (rnd, daysBack) => new Date(Date.now() - randInt(rnd, 0, daysBack) * 86_400_000);

/** Deterministic PRNG (mulberry32) so two runs produce the same dataset. */
function mulberry32(seed) {
  return function next() {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

async function seedDatabase({
  tasks = 100_000,
  workspaces = 20,
  users = 50,
  batch = 5_000,
  seed = 42,
  onProgress = () => {},
  wipe = true,
} = {}) {
  const rnd = mulberry32(seed);
  const started = Date.now();

  if (wipe) {
    await Promise.all([User, Workspace, Task, ActivityLog].map((M) => M.deleteMany({})));
  }

  // bcrypt with 4 rounds: seeding hashes one shared password, not 100k of them.
  const passwordHash = await bcrypt.hash('SeedPassword123!', 4);

  // Ids are generated HERE (not left to the driver) so the task documents can
  // reference the exact same ObjectIds without reading anything back.
  const userIds = Array.from({ length: users }, () => new mongoose.Types.ObjectId());
  const workspaceIds = Array.from({ length: workspaces }, () => new mongoose.Types.ObjectId());

  await User.insertMany(
    userIds.map((id, i) => ({
      _id: id,
      name: 'Seed User ' + String(i + 1).padStart(3, '0'),
      email: 'user' + (i + 1) + '@seed.local',
      passwordHash,
      avatarColor: '#' + Math.floor(rnd() * 0xffffff).toString(16).padStart(6, '0'),
    })),
    { ordered: false }
  );

  await Workspace.insertMany(
    workspaceIds.map((id, i) => ({
      _id: id,
      name: 'Workspace ' + String(i + 1).padStart(2, '0'),
      slug: 'workspace-' + String(i + 1).padStart(2, '0'),
      description: 'Seeded workspace number ' + (i + 1),
      owner: userIds[i % userIds.length],
      members: userIds.map((uid) => ({ user: uid, role: 'member', joinedAt: new Date() })),
    })),
    { ordered: false }
  );
  // The first user of each workspace owns it.
  await Workspace.collection.updateOne(
    { _id: workspaceIds[0] },
    { $set: { 'members.0.role': 'owner' } }
  );

  let inserted = 0;
  let done = 0;
  while (done < tasks) {
    const size = Math.min(batch, tasks - done);
    const docs = [];
    for (let i = 0; i < size; i += 1) {
      const status = pick(STATUSES, rnd);
      const due = randDate(rnd, 60);
      docs.push({
        workspace: pick(workspaceIds, rnd),
        title: 'Task ' + (done + i + 1) + ' - ' + pick(LABELS, rnd),
        description: 'Generated by scripts/seed.js for benchmarking.',
        status,
        priority: pick(PRIORITIES, rnd),
        assignee: pick(userIds, rnd),
        createdBy: pick(userIds, rnd),
        dueDate: due,
        completedAt: status === 'done' ? due : null,
        labels: [pick(LABELS, rnd)],
        createdAt: randDate(rnd, 365),
        updatedAt: new Date(),
      });
    }
    // Unordered bulkWrite: one round trip per batch, and MongoDB can apply the
    // operations in parallel instead of stopping at the first error.
    // eslint-disable-next-line no-await-in-loop
    const res = await Task.collection.bulkWrite(
      docs.map((document) => ({ insertOne: { document } })),
      { ordered: false }
    );
    inserted += res.insertedCount;
    done += size;
    onProgress({ inserted, total: tasks });
  }

  await Task.syncIndexes();

  return {
    users: userIds.length,
    workspaces: workspaceIds.length,
    tasks: inserted,
    userIds,
    workspaceIds,
    durationMs: Date.now() - started,
  };
}

module.exports = { seedDatabase, mulberry32 };
